"""empty message

Revision ID: 013e9585808c
Revises: 
Create Date: 2021-11-16 10:31:42.124025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013e9585808c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('rotation', sa.String(length=250), nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('id_properties', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_properties'], ['planets_properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_properties'),
    sa.UniqueConstraint('id_properties'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    op.drop_table('planets_properties')
    # ### end Alembic commands ###
