"""empty message

Revision ID: 6aa7a21a7783
Revises: 
Create Date: 2021-11-26 16:48:19.220829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa7a21a7783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details_starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('manufacturer', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('cost_in_credits', sa.FLOAT(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Height', sa.Integer(), nullable=False),
    sa.Column('Mass', sa.Integer(), nullable=False),
    sa.Column('Hair_color', sa.String(length=250), nullable=False),
    sa.Column('Birth_year', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.FLOAT(), nullable=False),
    sa.Column('rotation', sa.FLOAT(), nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('_is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('id_properties', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_properties'], ['people_properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_properties'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('id_properties', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_properties'], ['planets_properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_properties'),
    sa.UniqueConstraint('name')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('id_details', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_details'], ['details_starship.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_details'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorite_planet',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('planet_id', 'user_id')
    )
    op.create_table('favorite_starship',
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('starship_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_starship')
    op.drop_table('favorite_planet')
    op.drop_table('starships')
    op.drop_table('planets')
    op.drop_table('people')
    op.drop_table('user')
    op.drop_table('planets_properties')
    op.drop_table('people_properties')
    op.drop_table('details_starship')
    # ### end Alembic commands ###
