"""empty message

Revision ID: b6760582908f
Revises: 
Create Date: 2021-11-16 15:21:28.335618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6760582908f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detailsStarship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('manufacturer', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('cost_in_credits', sa.FLOAT(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('id_details', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_details'], ['detailsStarship.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_details'),
    sa.UniqueConstraint('id_details'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starships')
    op.drop_table('detailsStarship')
    # ### end Alembic commands ###
